# Generated by Django 5.0.3 on 2024-05-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(help_text='3-4 letter code of a UBC building', max_length=4)),
                ('building_name', models.CharField(help_text='Full name of a UBC building', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='Whether the room is a general or restricted space', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(help_text='UBC campus code', max_length=20)),
                ('building_code', models.CharField(help_text='3-4 letter code of a UBC building', max_length=4)),
                ('building_name', models.CharField(help_text='Full name of a UBC building', max_length=100)),
                ('room', models.IntegerField(help_text='Room number associated with the availability')),
                ('room_type', models.CharField(help_text='Whether the room is a general or restricted space', max_length=20)),
                ('start', models.DateTimeField(help_text="Start of the room availability in 'YYYY-MM-DD HH:MM'")),
                ('end', models.DateTimeField(help_text="End of the room availability in 'YYYY-MM-DD HH:MM'")),
            ],
        ),
    ]
