# Generated by Django 5.0.3 on 2024-05-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.CharField(default='UBCV', help_text='UBC campus code', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='campus',
            field=models.CharField(default='UBCV', help_text='UBC campus code', max_length=20),
            preserve_default=False,
        ),
    ]
