# Generated by Django 5.0.3 on 2024-05-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_building_campus_roomtype_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='campus',
            field=models.CharField(help_text='UBC campus code', max_length=4),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='campus',
            field=models.CharField(help_text='UBC campus code', max_length=4),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='campus',
            field=models.CharField(help_text='UBC campus code', max_length=4),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='room',
            field=models.CharField(help_text='Room number associated with the availability'),
        ),
    ]
