# Generated by Django 5.0.3 on 2024-11-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_populate_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='building_name',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_code',
            field=models.CharField(help_text='3-4 letter code of a UBC building', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(help_text='Full name of a UBC building', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(db_column='campus', help_text='Foreign key for UBC campus', max_length=4, on_delete=django.db.models.deletion.CASCADE, to='api.campus'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(help_text='UBC campus code', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='campus',
            field=models.ForeignKey(db_column='campus', help_text='Foreign key for UBC campus', max_length=4, on_delete=django.db.models.deletion.CASCADE, to='api.campus'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(help_text='Whether the room is a general or restricted space', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='building_code',
            field=models.ForeignKey(db_column='building_code', help_text='Foreign key for UBC building', max_length=4, on_delete=django.db.models.deletion.CASCADE, to='api.building'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='campus',
            field=models.ForeignKey(db_column='campus', help_text='Foreign key for UBC campus', max_length=4, on_delete=django.db.models.deletion.CASCADE, to='api.campus'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='room_type',
            field=models.ForeignKey(db_column='room_type', help_text='Foreign key for UBC room type', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='api.roomtype'),
        ),
    ]
