# Generated by Django 5.0.3 on 2024-11-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_building_building_address_add_building_longitude_add_building_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_address',
            field=models.CharField(db_default=None, default=None, help_text='Street address of a UBC building', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(db_default=None, decimal_places=6, default=None, help_text='Latitude data of a UBC building up to 5 significant figures', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(db_default=None, decimal_places=6, default=None, help_text='Longitude data of a UBC building up to 5 significant figures', max_digits=9, null=True),
        ),
    ]
