# Generated by Django 5.0.3 on 2024-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_building_building_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_address',
            field=models.CharField(db_default='', default='', help_text='Street address of a UBC building', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, help_text='Latitude data of a UBC building up to 5 significant figures', max_digits=8),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, help_text='Longitude data of a UBC building up to 5 significant figures', max_digits=9),
        ),
    ]
