services:
  db:
    image: ubcclassrooms/db:latest
    expose:
      - 5432
    env_file:
      - prod.env
    volumes:
      - ./backend/data/db_prod:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    image: ubcclassrooms/web:latest
    expose:
      - 8000
    env_file:
      - prod.env
    volumes:
      - ./backend:/src
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    image: ubcclassrooms/nginx:latest
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/frontend
      - ./certbot/www:/var/www/certbot/:ro
    restart: unless-stopped
    depends_on:
      - web
  
  certbot:
    image: ubcclassrooms/certbot:latest
    ports: 
      - 80:80
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/certs:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --email $${CERTBOT_EMAIL} -d ubcclassrooms.ca -d www.ubcclassrooms.ca --agree-tos
    depends_on:
      - nginx

  scrape-classrooms:
    image: ubcclassrooms/scrape-classrooms:latest
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
    command: python scripts/scrape_classrooms.py

  compute-timeslots:
    image: ubcclassrooms/compute-timeslots:latest
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python scripts/compute_timeslots.py

  create-models:
    image: ubcclassrooms/create-models:latest
    env_file:
      - prod.env
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python manage.py create_models
    depends_on:
      db:
        condition: service_healthy

  delete-expired-timeslots:
    image: ubcclassrooms/delete-expired-timeslots:latest
    env_file:
      - prod.env
    command: python manage.py delete_expired_timeslots
    depends_on:
      db:
        condition: service_healthy
      
  api-tests:
    image: ubcclassrooms/api-tests:latest
    env_file:
      - prod.env
    command: python manage.py test api.tests
    depends_on:
      db:
        condition: service_healthy