services:
  db:
    container_name: db
    image: postgres:16.3
    ports:
      - 5432:5432
    env_file:
      - test.env
    volumes:
      - ./backend/data/db_test:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  api-tests:
    container_name: api-tests
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - test.env
    command: python manage.py test api.tests
    depends_on:
      db:
        condition: service_healthy