services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src
    ports:
    - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
  scrape-classrooms:
    build: ./backend
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
    command: python scripts/scrape_classrooms.py
  compute-timeslots:
    build: ./backend
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python scripts/compute_timeslots.py
  api-test:
    build: ./backend
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - TEST_NAME=${TEST_NAME}
    command: python manage.py test api.tests
    depends_on:
      - db