services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    env_file:
      - prod.env
    options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/src
    ports:
    - "8000:8000"
    env_file:
      - prod.env
    depends_on:
      - db

  scrape-classrooms:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
    command: python scripts/scrape_classrooms.py

  compute-timeslots:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python scripts/compute_timeslots.py

  create-models:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - prod.env
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python manage.py create_models
    depends_on:
      - db

  delete-expired-timeslots:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - prod.env
    command: python manage.py delete_expired_timeslots
    depends_on:
      - db
      
  api-test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - prod.env
    command: python manage.py test api.tests
    depends_on:
      - db