services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    env_file:
      - dev.env

  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src
    ports:
    - "8000:8000"
    env_file:
      - dev.env
    depends_on:
      - db

  scrape-classrooms:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
    command: python scripts/scrape_classrooms.py

  compute-timeslots:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python scripts/compute_timeslots.py

  create-models:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    volumes:
      - ./backend/data/raw_booking_data:/raw_booking_data
      - ./backend/data/timeslot_data:/timeslot_data
    command: python manage.py create_models
    depends_on:
      - db

  delete-expired-timeslots:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    command: python manage.py delete_expired_timeslots
    depends_on:
      - db
      
  api-test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    command: python manage.py test api.tests
    depends_on:
      - db