services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - test.env
    environment:
      - POSTGRES_DB=$${SQL_DB}
      - POSTGRES_USER=$${SQL_USER}
      - POSTGRES_PASSWORD=$${SQL_PASSWORD}
    volumes:
      - ./backend/data/db_test:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $${SQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  api-tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - test.env
    command: python manage.py test api.tests
    depends_on:
      db:
        condition: service_healthy