"""
Names for UBC infrastructure used throughout the project
"""
from enum import Enum

class CampusEnum(Enum):
    UBCV = "Vancouver"
    UBCO = "Okanagan"



class ClassroomType(Enum):
    # Types of classrooms - "General" is for general teaching spaces that are open to all faculties, 
    #                       "Restricted" is for restricted spaces primarily reserved for a respective faculty
    GENERAL = "General"
    RESTRICTED = "Restricted"



class BuildingCodeToFullName(Enum):
    # Building codes for UBC buildings and their full names
    # Full names taken from UBC Learning Spaces when available, or misc. UBC sites

    ALRD = "Allard Hall"
    ANSO = "Anthropology and Sociology"
    AERL = "Aquatic Ecosystems Research Laboratory"
    ACEN = "Asian Centre"
    AUD = "Auditorium"
    AUDX = "Auditorium Annex"
    BINN = "B.C. Binning Studios"
    BIOL = "Biological Sciences"
    BUCH = "Buchanan"
    BUTO = "Buchanan Tower"
    CBH = "Centre for Brain Health"
    CHAN = "Chan Centre for the Performing Arts"
    CHBE = "Chemical and Biological Engineering Building"
    CHEM = "Chemistry"
    CIRS = "Centre for Interactive Research on Sustainability"
    CEME = "Civil and Mechanical Engineering"
    CEML = "Civil and Mechanical Engineering Laboratories"
    CHOI = "C.K. Choi Building"
    MINL = "Coal and Mineral Processing Laboratory"
    DLAM = "David Lam Building"
    DETW = "Detwiller Pavilion"
    DSOM = "Dorothy Somerset Studio"
    KENN = "Douglas Kenny"
    EOS = "Earth and Ocean Sciences"
    ESB = "Earth Sciences Building"
    FNH = "Food, Nutrition and Health"
    FSC = "Forest Sciences Centre"
    FORW = "Frank Forward"
    KAIS = "Fred Kaiser"
    FRWO = "Frederic Wood Theatre"
    FRDM = "Friedman Building"
    HORT = "UBC Botany Teaching Greenhouse"
    GEOG = "Geography"
    HEBB = "Hebb"
    HENN = "Hennings"
    ANGU = "Henry Angus"
    ICCS = "Institute for Computing, Information and Cognitive Systems"
    DMP = "Hugh Dempster Pavilion"
    IONA = "Iona Building"
    IKB = "Irving K. Barber Learning Centre"
    KOER = "Koerner Pavilion"
    LAX = "Landscape Architecture Annex"
    LASR = "Frederic Lasserre"
    LSK = "Leonard S. Klinck" 
    LSC = "Life Sciences Centre"
    LIU = "Liu Institute for Global Issues"
    LMRS = "Lower Mall Research Station"
    MCDN = "Macdonald"
    MCLD = "MacLeod"
    MCLM = "MacMillan"
    MATH = "Mathematics"
    MATX = "Mathematics Annex"
    MEDC = "Medical Sciences Block C"
    MGYM = "UBC War Memorial Gymnasium"
    MSL = "Michael Smith Laboratories"
    MUSC = "Music Building"
    SCRF = "Neville Scarfe"
    ORCH = "Orchard Commons"
    OSB2 = "Robert F. Osborne Centre"
    PHRM = "Pharmaceutical Sciences Building"
    PONE = "Ponderosa Annex E"
    PCN = "Ponderosa Commons North"
    PCE = "Ponderosa Commons East Audain Art"
    RITS = "Ritsumeikan-UBC House"
    SPPH = "School of Population and Public Health"
    STAO = "Sing Tao School of Journalism"
    TFPB = "Theatre-Film Production Building"
    TFS = "Totem Field Studios"
    UCEN = "Leon and Thea Koerner University Centre"
    LIFE = "UBC Life Building" 
    EDC = "Wayne and William White Engineering Design Centre"
    WESB = "Wesbrook"
    SWNG = "West Mall Swing Space"
    IRC = "P.A. Woodward Instructional Resources Centre"