"""
Names for UBC infrastructure used throughout the project
"""
from enum import Enum

class Campus(Enum):
    UBCV = "UBCV"



class ClassroomType(Enum):
    # Types of classrooms - "General" is for general teaching spaces that are open to all faculties, 
    #                       "Restricted" is for restricted spaces primarily reserved for a respective faculty
    GENERAL = "General"
    RESTRICTED = "Restricted"



class BuildingCode(Enum):
    # Building codes for UBC buildings and their full names
    
    ALRD = "Allard Hall"
    ANSO = "Anthropology and Sociology"
    AERL = "Aquatic Ecosystems Research Lab"
    ACEN = "Asian Centre"
    AUD = "Auditorium"
    AUDX = "Auditorium Annex"
    BINN = "B.C. Binnings Studio"
    BIOL = "Biological Sciences"
    BUCH = "Buchanan"
    BUTO = "Buchanan Tower"
    CBH = "Centre for Brain Health"
    CHAN = "Chan Ctr Performing Arts"
    CHBE = "Chemical and Biological Engineering"
    CHEM = "Chemistry"
    CIRS = "CIRS"
    CEME = "Civil and Mechanical Eng."
    CEML = "Civil and Mechanical Eng. Labs"
    CHOI = "CK Choi"
    MINL = "Coal and Mineral Processing"
    DLAM = "David Lam Building"
    DETW = "Detwiller Pavilion"
    DSOM = "Dorothy Somerset Studio"
    KENN = "Douglas Kenny"
    EOS = "Earth and Ocean Sciences"
    ESB = "Earth Sciences"
    FNH = "Food, Nutrition and Health"
    FSC = "Forest Sciences Centre"
    FORW = "Frank Forward"
    KAIS = "Fred Kaiser"
    FRWO = "Frederic Wood Theatre"
    FRDM = "Friedman"
    HORT = "Greenhouse(Horticultural Bldg)"
    GEOG = "Geography"
    HEBB = "Hebb"
    HENN = "Hennings"
    ANGU = "Henry Angus"
    ICCS = "ICCS"
    DMP = "Hugh Dempster Pavilion"
    IONA = "Iona"
    IKB = "Irving K. Barber Learning Ctr"
    KOER = "Koerner Pavilion"
    LAX = "Landscape Architecture Annex"
    LASR = "Lasserre"
    LSK = "Leonard S Klinck" 
    LSC = "Life Sciences Centre"
    LIU = "Liu Institute"
    LMRS = "Lower Mall Research Station"
    MCDN = "Macdonald"
    MCLD = "MacLeod Building"
    MCLM = "MacMillan"
    MATH = "Mathematics"
    MATX = "Mathematics Annex"
    MEDC = "Medical Block C"
    MGYM = "Memorial Gymnasium"
    MSL = "Michael Smith Laboratories"
    MUSC = "Music"
    SCRF = "Neville Scarfe"
    ORCH = "Orchard Commons"
    OSB2 = "Osborne Centre"
    PHRM = "Pharmaceutical Sciences"
    PONE = "Ponderosa Annex E"
    PCN = "Ponderosa Commons North"
    PCE = "Ponderosa Commons East Audain Art"
    RITS = "Ritsumeikan-UBC House"
    SPPH = "School Populatn & Publc Hlth"
    STAO = "Sing Tao School of Journalism"
    TFPB = "Theatre-Film Production Building"
    TFS = "Totem Field Studios"
    UCEN = "Leon & Thea Koerner University Centre"
    LIFE = "UBC Life Building" 
    EDC = "Wayne & William White Engineering Design Centre"
    WESB = "Wesbrook"
    SWNG = "West Mall Swing Space"
    IRC = "Woodward IRC"