name: ci

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  api-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create testing env file
        run: |
          touch test.env
          echo SQL_ENGINE=${{ secrets.SQL_ENGINE }} >> test.env
          echo SQL_DB=${{ secrets.SQL_DB }} >> test.env
          echo SQL_DB_TEST=${{ secrets.SQL_DB_TEST }} >> test.env
          echo SQL_USER=${{ secrets.SQL_USER }} >> test.env
          echo SQL_PASSWORD=${{ secrets.SQL_PASSWORD }} >> test.env
          echo SQL_HOST=${{ secrets.SQL_HOST }} >> test.env
          echo SQL_PORT=${{ secrets.SQL_PORT }} >> test.env
          echo DB=${{ secrets.DB }} >> test.env
          echo DEBUG=1 >> test.env
          echo DJANGO_ALLOWED_HOSTS=* >> test.env
          echo DJANGO_TEST_SECRET_KEY=${{ secrets.DJANGO_TEST_SECRET_KEY}} >> test.env

      - name: Build images
        run: docker compose -f compose.test.yml build db api-tests

      - name: Start DB service
        run: docker compose -f compose.test.yml up db -d --wait

      - name: Run API tests
        run: docker compose -f compose.test.yml run api-tests
      
      - name: Dump Docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.2
