name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  api-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build image
        run: docker compose build
      - name: Run API tests
        run: docker compose run api-test
