name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  api-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}} 
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME}} 
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      TEST_NAME: ${{ secrets.TEST_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        run: docker compose build
      - name: Start DB service
        run: docker compose up db -d
      - name: Wait for DB connection
        run: sleep 10
      - name: Run API tests
        run: docker compose run api-test
