name: tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  api-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    container:
      image: python:latest
      volumes:
        - ${{ github.workspace }}:.

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
