name: Update database from UBC Online Timetable

on:
    schedule:
        # Run once a week on Monday at 12:30 AM
        - cron: "30 0 * * 1"

jobs:
    update-database:
        name: Update database
        runs-on: ubuntu-latest
        environment: production
        env:
            VPN_HOST: ${{ secrets.VPN_HOST }}
            VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
            VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}

        steps:
            - name: SSH into production server and update database
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                passphrase: ${{ secrets.SSH_PASSPHRASE }}
                envs: VPN_HOST,VPN_USERNAME,VPN_PASSWORD
                script: |
                    # Change directory to project
                    cd /
                    cd srv/ubc-classrooms
                    # Connect to UBC VPN
                    /opt/cisco/anyconnect/bin/vpn -s <<"EOF"
                    connect $VPN_HOST
                    $VPN_USERNAME
                    $VPN_PASSWORD
                    EOF
                    # Scrape data from UBC Online Timetable
                    docker-compose -f compose.prod.yml run scrape-classrooms
                    # Disconnect from UBC VPN
                    /opt/cisco/anyconnect/bin/vpn disconnect
                    # Compute timeslots from scraped data
                    docker-compose -f compose.prod.yml run compute-timeslots
                    # Write timeslots to database
                    docker-compose -f compose.prod.yml run create-models
                    # Cleanup expired timeslots
                    docker-compose -f compose.prod-yml run delete-expired-timeslots